# Generated by Django 5.1.6 on 2025-02-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knb', '0003_user_last_login_alter_user_login_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
    ]
