# Generated by Django 5.1.6 on 2025-02-28 19:43

import knb.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knb', '0004_rename_login_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', knb.models.CustomUserManager()),
            ],
        ),
    ]
