# Generated by Django 5.1.6 on 2025-02-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knb', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games_total',
            field=models.IntegerField(default=0),
        ),
    ]
