# Generated by Django 5.1.6 on 2025-03-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knb', '0009_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://img.icons8.com/ios-filled/100/FFFFFF/user-male-circle.png', null=True, upload_to='profile_pics/'),
        ),
    ]
